// <auto-generated />
using System;
using HealthReport.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthReport.Infrastructure.Migrations
{
    [DbContext(typeof(HealthReportDbContext))]
    [Migration("20251228184806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthReport.Domain.Entities.BloodGlucoseMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BGValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Meal")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("MeasuredTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BloodGlucoseMeasurements");
                });

            modelBuilder.Entity("HealthReport.Domain.Entities.BloodPressureMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Diastolic")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("MeasuredTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("Systolic")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekOfYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BloodPressureMeasurements");
                });

            modelBuilder.Entity("HealthReport.Domain.Entities.WeightMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BMI")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("BodyWaterPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("MeasuredTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SkeletalMuscleMassKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("WeightChangeKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.ToTable("WeightMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
