using HealthReport.Application.Contracts.Imports;
using HealthReport.Application.FileParsers;

namespace HealthReport.Application.Handlers.Imports;

/// <summary>
/// Marker interface for import handlers.
/// 
/// TODO: Refactoring required, generated by AI
/// </summary>
public interface IImportHandler
{
    Task<ImportResultDto> ImportAsync(Stream stream, bool hasHeader = true, CancellationToken cancellationToken = default);
}